### ISSUE TITLE
Services page drop down menu suggestion

### ISSUE THREAD

**Issue by rubyrat** [verifa/website#39]
Only have the title in the dropdown menu, ie remove short description as it's not all visible on smaller screens
<img width="804" alt="Screenshot 2022-08-18 at 16 35 23" src="https://user-images.githubusercontent.com/31657652/185408857-6f4088cd-74f8-4299-a03a-c84b8b2add32.png">
.

**Comment by jlarfors** [comment]
This change was made at some point... Closing.
