### ISSUE TITLE
Text misaligned for Value Stream wastes 

### ISSUE THREAD

**Issue by jlarfors** [verifa/website#85]
On the CD workshop page: https://verifa.io/work/continuous-delivery-workshop/

Under "Types of waste." the wastes are not aligned properly with the icons. See the below screenshot.

![image](https://github.com/verifa/website/assets/1135394/5723f613-6ac5-48f7-b1f2-ee5015ac9043)

**Comment by commitsovercoffee** [comment]
@jlarfors Hello. Apart from the issue mentioned above, I saw some similar minor issues on the site. Can you please confirm if I should fix any of the below ( along with one you mentioned ) ? Will fix it all in the same PR.

- [ ] 1. The **Learn More** buttons should horizontally aligned across cards ? On [home](https://verifa.io/) page.

![image](https://github.com/verifa/website/assets/129554482/5243ee22-e3d3-47f8-8bf3-8940135e85b7)


- [ ] 2. Shouldn’t the companies names be horizontally aligned across cards ? On [clients](https://verifa.io/clients/) page.

![image](https://github.com/verifa/website/assets/129554482/d7009a7c-b9f4-45e0-a4ce-d3f96bb06be5)

- [ ] 3. Shouldn’t the _continuous delivery principle_  label and > icon be horizontally aligned ? On [cd workshop](https://verifa.io/work/continuous-delivery-workshop/) page.

![image](https://github.com/verifa/website/assets/129554482/c75e2d83-f315-4bba-8597-72a9206ec584)

- [ ] 4. I feel there should be more gap between the project description & tags. On [projects](https://verifa.io/projects/) page.

![image](https://github.com/verifa/website/assets/129554482/33c3e8a8-ad41-4856-8be5-71d65235354a)
